### ISSUE TITLE
Deb package should not replace configs

### ISSUE THREAD

**Issue by janisz** [allegro/marathon-consul#113]
When you install marathon-consul from deb it will overwrite `/etc/marathon-consul.d/config.json`. Instead user should be asked what should happen.

https://www.debian.org/doc/debian-policy/ch-files.html#s-config-files

**Comment by ojagodzinski** [comment]
My idea is to change the name of default config created by .deb package to something like /etc/marathon-consul.d/config.json.template. Only downside is that new installations won't be as smooth as they are now.

**Comment by janisz** [comment]
I think adding this file to conffiles should be enough but can't verify it now :(

**Comment by ojagodzinski** [comment]
conffiles is also good idea but goxc doesn't support conffiles/postinst files.

**Comment by janisz** [comment]
[goxc #86](https://github.com/laher/goxc/issues/86) suggest using fpm for generating debs. I think we can go with template option. It won't change current behavior becouse deb config is generated from default values so there shouldn't be any change in deb installation behavior. 
@ojagodzinski Would you like to prepare pull request for it?

**Comment by janisz** [comment]
Prepared PR for debber https://github.com/debber/debber-v0.3/pull/2 (part of goxc used for creating debs). Once it's get merged we need to apply following patch 
```diff
diff --git a/resources/debian/conffiles b/resources/debian/conffiles
new file mode 100644
index 0000000..834b1ae
--- /dev/null
+++ b/resources/debian/conffiles
@@ -0,0 +1,3 @@
+/etc/init/marathon-consul.conf
+/etc/marathon-consul.d/config.json
+/etc/systemd/system/marathon-consul.service
```

**Comment by janisz** [comment]
It looks like debber and goxc is no logner maintained and my fix is not enought. I'll try incorporate fpm. 
Thanks @ojagodzinski for pointing out the problem and help with fpm

```bash
fpm --verbose -s dir -t deb \                                                          
        -n marathon-consul \
        -v 1.0.0-alpha7 \
        --url="https://github.com/allegro/marathon-consul" \
        --vendor=Allegro \
        --maintainer="Allegro Group <opensource@allegro.pl>" \
        --description "Marathon-consul service (performs Marathon Tasks registration as Consul Services for service discovery) Marathon-consul takes information provided by the Marathon event bus and forwards it to Consul agents. It also re-syncs all the information from Marathon to Consul on startup and repeats it with given interval." \
        --deb-priority optional \
        --workdir /tmp/ \
        --license "Apache License, version 2.0" \
        ./bin/marathon-consul=/usr/bin/marathon-consul \
        ./debian/marathon-consul.service=/etc/systemd/system/marathon-consul.service \
        ./debian/marathon-consul.upstart=/etc/init/marathon-consul.conf \
        ./debian/config.json=/etc/marathon-consul.d/config.json
```
