### ISSUE TITLE
Drop not supported events

### ISSUE THREAD

**Issue by janisz** [allegro/marathon-consul#139]
Currently we are using only 2 events `status_update_event` and `health_status_changed_event`. Marathon has about 30 implementations of [`MarathonEvent`](https://github.com/mesosphere/marathon/blob/0f132000a53e8a14713b28f4a86d515876b88ec6/src/main/scala/mesosphere/marathon/core/event/Events.scala#L14) and all that events could be sent to marathon-consul. Some events are big and Marathon doesn't allow filtering events befor sent (see [#3154](https://github.com/mesosphere/marathon/issues/3154)). There is no point in pushing all events into event queue. Better drop all unwanted events before they gets to queue.

**Comment by dankraw** [comment]
Maybe we should introduce some `event-max-size` (in bytes) configuration property? We already know that only few event types are problematic / large and could be safely filtered as these types are already ignored by m-c (since 1.0.0). This way we would not have to parse them at all.

**Comment by janisz** [comment]
I started with similar approach. Instead of checking event size I'm searching for event name. Another change I will introduce is to parse event once only if it has proper type. I'll gather testing data and prepare benchmark to measure improvements.
