### ISSUE TITLE
Support Marathon SSE

### ISSUE THREAD

**Issue by janisz** [allegro/marathon-consul#143]
Since there are rumors about deprecating http callbacks and their limited throughput and performance footprint we need to consider implementing [SSE support](http://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-events).

As @kamilchm [proposed](https://github.com/allegro/marathon-consul/pull/140#issuecomment-261197732) when [marathon#4637](https://github.com/mesosphere/marathon/issues/4637) ([marathon#4671](https://github.com/mesosphere/marathon/pull/4671)) will be solved we can significantly reduce network traffic and network connections in comparision to callbacks.

**Comment by janisz** [comment]
We should support multiple m-c instances for HA. To do it we need to prevent them from running all at once. We already has consul cluster so we can use it to elect one running instance and suspend others. This will prevent us from having many opened  SSE connections and concurrent updates. 
[Here](https://distributedbydefault.com/distributed-locks-with-consul-and-golang-c4eccc217dd5#.6j6eip45n) is nice post about using Consul for distributed locks

**Comment by adamdubiel** [comment]
Okay, so are we going with Consul as leader-elector? Fine by me, too bad we need to code those locks from scratch.

**Comment by kamilchm** [comment]
https://github.com/minio/dsync

**Comment by mhamann** [comment]
This appears to be a simple, but useful lib for connecting to and handling SSEs: https://github.com/andrewstuart/go-sse
