### ISSUE TITLE
1.2.0 .deb package not properly signed

### ISSUE THREAD

**Issue by giannello** [allegro/marathon-consul#188]
Trying to install marathon-consul 1.2.0 from debian packages fails with the following error

```
The following packages cannot be authenticated!
      marathon-consul
```

**Comment by janisz** [comment]
Thanks. This bug is really annoying. Related to #90. It looks like bintray does not support signing binaries in one POST and need some time to process publish and and signing binaries needs to be delayed. Should be working now.
