### ISSUE TITLE
Sync is failling when no agents stored in cache

### ISSUE THREAD

**Issue by tomez** [allegro/marathon-consul#191]
In rare cases when marathon-consul is commencing sync there could be no agents available in the cache. For example just after start-up.

It results in following error:

```json
{
  "error" : "Can't get Consul services: No Consul client available in agents cache",
  "level" : "error",
  "msg" : "An error occured while performing sync",
  "time" : "2017-02-28T10:44:15+01:00"
}
```

And sync is dropped.

This is happening because agent cache is fed on registrations and de-registrations. While sync at the beginning is calling for list of applications and to do that agent cache must not be empty.

Summarizing: no register/de-register before sync -> marathon-consul will fail on sync.

To resolve, we could place consul-master in configuration as a fall-back agent-replacement and use in the case of nil cache.

**Comment by janisz** [comment]
> Summarizing: no register/de-register before sync -> marathon-consul will fail on sync.

It's not true. Sync is first task marathon-consul does after start. If there is no marathon-consul's task in Marathon then agents cache will not be populated and this error will happen. 

We can solve it by adding `--consul-agent-location` parameter so we always have at leas one agent in cache.

**Comment by xueyi28** [comment]
how to add --consul-agent-location parameter?

**Comment by janisz** [comment]
It needs to be added in [`consul.Config`](https://github.com/allegro/marathon-consul/blob/master/consul/config.go#L5) handle this flag in [`config.parseFlags`](https://github.com/allegro/marathon-consul/blob/master/config/config.go#L64) and finally add this agent to agents map in [`agents.NewAgents(config *Config)`](https://github.com/allegro/marathon-consul/blob/master/consul/agents.go#L40)

**Comment by hokiegeek2** [comment]
Hey, I am getting tripped up by this as well. 

I have marathon-consul running as a Marathon task with the following args:  --marathon-location=server1:8080 --marathon-leader=server2:8080 --sse-enabled=true

I can see the Marathon events coming into the logs but the corresponding marathon apps are not being registered or de-registered in consul. Here are the error messages I get:

Syncing services started
"An error occured while performing sync" error="Can't get Consul services: No Consul client available in agents cache"

"There was a problem deregistering task" ... error="No Consul client available in agents cache"

Also, consul is receiving TASK_RUNNING events, but not registering

Any ideas?

--John

**Comment by janisz** [comment]
@hokiegeek2  Marathon-Conusl will not register task (and populate agents cache) if task is has not `consul` label. Can you add more logs?

**Comment by hokiegeek2** [comment]
@janisz Thanks so much for responding so quickly! I really appreciate it. This looks like a great tool and I am looking forward to getting it running correctly.

I apologize, I should have been more precise in my question. I have one marathon task labeled "consul=jupyterhub-nginx" which is the task I am looking for and I am pegging it to a node that has a mesos slave and consul agent. Finally, I have marathon-consul running on all four of my Marathon masters. marathon-consul is deployed in Docker containers that are launched locally, not via Marathon with the args I specified above, although I did set the log-level to debug as well.

When I start the jupyterhub-nginx in Marathon I get two messages in the marathon-consul logs:
level="info" msg="Got StatusEvent" Id=jupyterhub-nginx******** TaskStatus="TASK_RUNNING"
level="debug" msg="Not handled task status" Id=jupyterhub-nginx******** taskStatus="TASK_RUNNING"

In Consul I see the node I am launching the Marathon task on is listed node with an agent health status of "Agent alive and reachable", but I don't see my task

So the marathon events are being sent to and acknowledged by marathon-consul, but the corresponding marathon tasks are not being registered with Consul.

--John

**Comment by janisz** [comment]
@hokiegeek2 Your task is not registered because marathon-consul registers only when task becomes healthy. Did you specify health check for task?

> [The task is registered when Marathon marks it as alive.](https://github.com/janisz/marathon-consul#task-healthchecks)

**Comment by hokiegeek2** [comment]
@janisz Yay! That was it! Many apologies for missing this in the docs. Thanks!

--John

**Comment by janisz** [comment]
No problem. Created issue for updating the readme https://github.com/allegro/marathon-consul/issues/221

**Comment by xueyi28** [comment]
1. marathon app is running , it is have a label ["consul": ""]
2. consul agent must open 8500 port, and consul-marathon can connect to consul agent 
3. marathon app must have a health check

**Comment by janisz** [comment]
@xueyi28  我不会说中文 
I can't speak Chinese. Could you please translate?
