### ISSUE TITLE
marathon leader should be retrieved from Marathon on startup

### ISSUE THREAD

**Issue by hokiegeek2** [allegro/marathon-consul#228]
Hi Everyone,

First of all, marathon-consul is a great product--well done! I've been running it for a week and it's working exactly as advertised. 

The only area of concern is that the marathon-leader config parameter is static and therefore marathon-consul could fail on a restart if the marathon leader changes. If the marathon-leader parameter is replaced with a call to the /v2/leader REST endpoint this would ensure correct configuration in the event of a marathon leader change.

Thanks

--John

**Comment by janisz** [comment]
We are relaying on marathon-leader to determine leader of Marathon-Consul. We are running marathon-consul on nodes where Marathon is running. This give us necessary HA when one marathon-nodes goes down, new leader will be elected and new m-c instance will start de/registering services.

If we allow m-c to connect to master this could lead to multiple m-c de/registering services and this should cause race condition between them especially during sync.

One option is to connect to current marathon leader when marathon-leader is empty but IMO better if we provide more verbose way to force marathon-consul to work even if it's not connected to current leader. Sam as we did for [sync](https://github.com/allegro/marathon-consul#sync) - `sync-force`.

**Comment by hokiegeek2** [comment]
Okay, I may be missing something, but when I start marathon-consul and the marathon-leader value is incorrect (such as in the case that the marathon leader changes), resulting error messages indicate marathon-consul cannot find the leader and presumably marathon-consul does not work.

**Comment by tomez** [comment]
In HA installation You should have one marathon-consul instance per `Marathon`, as a side-car on the same node, each configured with different marathon-leader option (preferably local). So when leading marathon change, other m-c should take leading role as well.

Multiple `Marathons` and one m-c, is not supported setting, we will probably make this work in the future.

**Comment by hokiegeek2** [comment]
I do have one marathon-consul co-located with each marathon server. When I configure marathon-leader=localhost:8080 on the box hosting the marathon leader I get the message "I am not leader". The only time I don't get the message "I am not leader" is when I statically configure marathon-leader to the IP address/dns:8080 of the box hosting marathon leader.

Again, I may be missing something, but it's not obvious to me. Do you have an HA example config you can share?

**Comment by janisz** [comment]
> I do have one marathon-consul co-located with each marathon server.

:white_check_mark: 

> When I configure marathon-leader=localhost:8080 on the box hosting the marathon leader I get the message "I am not leader".

:x: `marathon-leader` should be set to marathon hostname as described below:

>  [Note that there is a difference between marathon-leader and marathon-location: marathon-leader is used for node leadership detection (should be set to cluster-wide node name), while marathon-location is used for connection purpose (may be set to localhost)](https://github.com/allegro/marathon-consul#sync).

**Comment by hokiegeek2** [comment]
Okay, so I am back to the original problem. We are running a four-node Marathon cluster in HA mode with leader election. The marathon leader can change via election at any time. Consequently, the CLI option for marathon-leader will be incorrect unless there's a means for retrieving the marathon leader at startup as well as when the sync fails with the message "I am not leader".

**Comment by janisz** [comment]
It's not a problem. If new node will be elected as a leader then marathon-consul runnign on this host will perform sync.

**Comment by guilhem** [comment]
@hokiegeek2 maybe it can help:
you can now use `marathon-leader=*` to always act like a leader.

It's really helpful if you only have 1 instance of _marathon-consul_.
(any marathon instance not leader will act as a proxy)

**Comment by janisz** [comment]
@hokiegeek2 Can I close this issue?

**Comment by hokiegeek2** [comment]
@janisz Absolutely, thanks for working the issues I raised in my testing. marathon-consul is working really well for us now.
