### ISSUE TITLE
marathon-consul loses connectivity to marathon

### ISSUE THREAD

**Issue by hokiegeek2** [allegro/marathon-consul#243]
Hi Everyone,

I don't see an open ticket on this, so I doubt anyone else is seeing this (and I cannot replicate on my five-node cluster at home). With 1.3.3 on my work cluster marathon-consul periodically loses connectivity to marathon with connection refused exceptions. marathon-consul restarts five times--each time logging that it is getting a connection refused from marathon--eventually staying in a connection refused state and therefore failing to capture marathon events from the event stream.

Maybe marathon-consul should continue to attempt to reconnect as opposed to getting into a state where it gives up?

--John

**Comment by janisz** [comment]
Thanks for reporting. I'll grep our logs to see if we experience similar problems. I think we have similar error when upgrading marathon and when we have network maintenance issues. 

> marathon-consul restarts five times--each time logging that it is getting a connection refused from marathon--eventually staying in a connection refused state and therefore failing to capture marathon events from the event stream.

Did marathon-consul stay in failing state? After 5 retires it should shut down. With some supervisor configured it should be restarted and fail again if problem wasn't fixed.

**Comment by hokiegeek2** [comment]
@janisz It restarted 4-5 times (I forget) and then remained up with the last logging statement being connection refused by marathon.

**Comment by janisz** [comment]
It shouldn't  works like this. Can you share the logs? I'll try to reproduce it in test and fix it.

**Comment by hokiegeek2** [comment]
Sure thing, will do so when I get back in the office tomorrow

**Comment by janisz** [comment]
I've checked our logs and we have logged

> Leader poll failed. Check marathon and previous errors. Exiting

AFAIR we don't have a situation when marathon-consul hangs in unconnected state. @tomez Do you recall this situation?/

**Comment by tomez** [comment]
Marathon-consul definitely shouldn't stay in disconnected state. 

@janisz I cant remember that situation ever happened and I am pretty sure we would notice it because in that case our registrations would simply stop working after any marathon downtime (eg. update).

After janisz investigation I can't add anything more right now.
@hokiegeek2 if You could reproduce it, and provide log info we will investigate further.

**Comment by hokiegeek2** [comment]
@janisz Here's the log messages of interest:

time="2017-06-16T19:50:14Z" level=error msg="Error when parsing the event" error=EOF
time="2017-06-16T19:50:14Z" level=error msg="This should never happen. Not handled event type" EventType= error="Unsuported event type: "
time="2017-06-16T19:50:14Z" level=fatal msg="Unable to recover streamer" error="Get http://localhost:8080/v2/events?event_type=status_update_event&event_type=health_status_changed_event: dial tcp 127.0.0.1:8080: getsockopt: connection refused"

USUAL STARTUP MESSAGES

**time="2017-06-16T19:50:14Z" level=warning msg="Error on http request" Location="localhost:8080" Protocol=http error="Get http://localhost:8080/v2/events?embed=apps.tasks&label=consul: dial tcp 127.0.0.1:8080: getsockopt: connection refused" statusCode="???"
time="2017-06-16T19:50:14Z" level=error msg="An error occured while performing sync" error="Can't get Marathon apps: Get http://localhost:8080/v2/events?embed=apps.tasks&label=consul: dial tcp 127.0.0.1:8080: getsockopt: connection refused"
time="2017-06-16T19:50:15Z" level=debug msg="Leader detection disable"
time="2017-06-16T19:50:15Z" level=info msg=Listening Port=":4000"
time="2017-06-16T19:50:15Z" level=error msg="Unable to start streamer" error="Get http://localhost:8080/v2/events?embed=apps.tasks&label=consul: dial tcp 127.0.0.1:8080: getsockopt: connection refused"**

USUAL STARTUP MESSAGES plus bolded logging block repeated 3 times, and then on the third time logging stops at: 

time="2017-06-16T19:50:20Z" level=error msg="Unable to start streamer" error="Get http://localhost:8080/v2/events?embed=apps.tasks&label=consul: dial tcp 127.0.0.1:8080: getsockopt: connection refused"

No further log messages, app is hung, no marathon events for consul-tagged Marathon tasks are captured

**Comment by hokiegeek2** [comment]
@tomez Thanks for investigating! Just provided the salient log messages, just restarted marathon-consul and I'll confirm if the same scenario repeats

**Comment by janisz** [comment]
@hokiegeek2 Thanks for logs. I can confirm there is a bug. The log you provided comes from [sse/sse_handler.go](https://github.com/allegro/marathon-consul/blob/1.3.3/sse/sse_handler.go#L61) a [couple lines above we have similar log but with Fatal](https://github.com/allegro/marathon-consul/blob/1.3.3/sse/sse_handler.go#L37). 

The problem you described do not occur when Marathon Master detection is enabled because detector can't connect to marathon so the streamer is not created. In your case streamer is created but it can't connect to marathon so it waits forever for events to handle but the events won't come because it's not connected.

We should not swallow connection error but propagate it to a caller and handle in [main.go](https://github.com/allegro/marathon-consul/blob/1.3.3/main.go#L47). We will provide a patch for this shortly.

**Comment by hokiegeek2** [comment]
@janisz That's awesome, thanks!

**Comment by hokiegeek2** [comment]
@janisz @tomez So I am noticing that we will get periodic connection refused errors in our Marathon cluster nodes. I see from the logging timing that marathon-consul attempts to connect very quickly--the first couple apparently within a second, which appears to be within the window of time that marathon refuses connections.

Perhaps what is needed is a configurable retry time interval for marathon connection failures?

**Comment by janisz** [comment]
@hokiegeek2 Could you please create separated ticket for configurable retry time interval / reconnect policy?

**Comment by hokiegeek2** [comment]
@janisz will do!

**Comment by hokiegeek2** [comment]
@janisz This works great! I deployed the patch and either marathon-consul recovers from loss of connectivity or exits after four failed tries. Since I am running marathon-consul as a service, it simply restarts and continues working. Thanks for implementing this patch so quickly.
