### ISSUE TITLE
please add configurable number of retries/retry interval for marathon connection errors

### ISSUE THREAD

**Issue by hokiegeek2** [allegro/marathon-consul#246]
I marathon-consul gets a connection refused error from marathon, it currently restarts 4 times very quickly--1-2 seconds--which may not give marathon time to reset. A configurable number of marathon connection retries and retry time interval for marathon connection failures would (hopefully) account for situations where there are intermittent marathon connectivity issues

**Comment by janisz** [comment]
It looks like there was intention to do it. SSE config has fields for configuring retries and backoff https://github.com/allegro/marathon-consul/blob/1.3.4/sse/config.go#L5-L6 this varaibles are set only when config is parsed from JSON. We should expose them in command line and describe in README.
