### ISSUE TITLE
Syncing the TASK_KILLING servcies

### ISSUE THREAD

**Issue by cynial** [allegro/marathon-consul#265]
Hi,

I enable TASK_KILLING feature ( run marathon with ` --enable_features task_killing` option) for better service discovery, Marathon-consul can handle the TASK_KILLING services, that's good. But the scheduled sync will sync the TASK_KILLING services also, it'll cause the traffic still route to the killing service. I need the scheduled sync feature, but how can I fix this issue?

**Comment by janisz** [comment]
@cynial Thanks for reporting. Are the below steps describes the problem?

1. An instance is up and running and registered in Consul.
2. The instance gets KILL event. Marathon sent TASK_KILLING event and application was deregistered from Consul.
3. While the instance was still in killing state marathon-consul performed sync and registered application.

**Comment by cynial** [comment]
Exactly.

**Comment by janisz** [comment]
The change should be done in [`func (t Task) IsHealthy() bool`](https://github.com/allegro/marathon-consul/blob/81db6e70d3946e25fbabf4a913ee1ee48d3950a3/apps/task.go#L66-L75) where we check if a task is healthy – all health checks passed. We need to add there additional condition checking if [`TaskStatus`](https://github.com/allegro/marathon-consul/blob/81db6e70d3946e25fbabf4a913ee1ee48d3950a3/apps/task.go#L16) is running (I assume we only want to register tasks that are running).

@cynial Would you like to work on this?

**Comment by cynial** [comment]
OK, I'm not familiar with GO, but will hava a try.

**Comment by janisz** [comment]
Fixed by #266
