### ISSUE TITLE
Migrate from Glide to dep

### ISSUE THREAD

**Issue by janisz** [allegro/marathon-consul#267]
It looks like https://github.com/golang/dep is going to be a standard way of maintaining dependencies in Golang projects.

### TODO

- [ ] Genrate dep metada files (Gopkg.lock and Gopkg.toml)
- [ ] Delete glide's metadata files ([glide.lock](https://github.com/allegro/marathon-consul/blob/1.4.1/glide.lock) and [glide.yml](https://github.com/allegro/marathon-consul/blob/1.4.1/glide.yaml))

Refs:
* https://github.com/kubernetes-incubator/node-feature-discovery/pull/76
* https://github.com/coreos/docs/issues/775
* https://github.com/inadarei/justgo/issues/4

**Comment by fortrieb** [comment]
Can i grep this issue?

**Comment by janisz** [comment]
@fortrieb It's yours :)
