### ISSUE TITLE
Update Consul to 1.0.0

### ISSUE THREAD

**Issue by janisz** [allegro/marathon-consul#271]
We should do #270 first. Then release marathon-consul and finally perform same steps to update to 1.0. There might be some breaking changes so the code might need some fixes. Finally, we should check if Marathon-Consul is backwards compatible with Consul 0.9.3. And if everything is ok we may create a new release.

**Comment by shayangz** [comment]
any plans on merging this PR and cutting a release?

Consul 1.1.0 [removed](https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#110-may-11-2018) the deprecated `script` checks which is breaking marathon-consul checks.

**Comment by pbetkier** [comment]
We're already on Consul 1.2.0 as of #288.
