### ISSUE TITLE
marathon-consul sometimes failing updation

### ISSUE THREAD

**Issue by sujithvs74** [allegro/marathon-consul#282]
marathon-consul sometimes failing in updating latest data in consul server. Whenever I face this issue, I need to restart marathon-consul container to update latest data. What will be the possible reasons for this issue. How can I troubleshoot this, do we have any logs for this?

**Comment by janisz** [comment]
@sujithvs74 Thanks for reporting! We do not experience similar issue... or we are not aware of it :)

Could you describe your setup, present configuration and logs? When does it happen? Have you got any idea how to reproduce it?
