### ISSUE TITLE
Using IP address instead of hostname as ServiceAddress

### ISSUE THREAD

**Issue by adamdubiel** [allegro/marathon-consul#41]
marathon-consul uses FQDN as a ServiceAddress instead of IP address when registering in Consul. Using FQDN makes no sense here.

**Comment by janisz** [comment]
I think it was changed to FQDN by purpose. @dankraw do you remember why we do it that way?

**Comment by dankraw** [comment]
Hmm, I don't remember if we used IPs before. We pass task's `host` property as it's the only thing we get from Marathon: https://github.com/allegro/marathon-consul/blob/master/consul/consul.go#L169

**Comment by dankraw** [comment]
OK, I know - in my local (vagrant) environment I get IPs as the `host` field.

**Comment by janisz** [comment]
I think it's because Mesos configuration.
