### ISSUE TITLE
Application runtime metrics

### ISSUE THREAD

**Issue by janisz** [allegro/marathon-consul#47]
Currently only domain specific metrics are exported to graphite. It'll be great if we can enable [MemStats](https://golang.org/pkg/runtime/#MemStats) and [GCStats](https://golang.org/pkg/runtime/debug/#GCStats)

**Comment by dankraw** [comment]
:+1:

**Comment by pawelszymczyk** [comment]
I could try do it for you.

**Comment by janisz** [comment]
![http://www.rogersv.com/wp-content/uploads/2014/01/try-not.jpg](http://www.rogersv.com/wp-content/uploads/2014/01/try-not.jpg)
