### ISSUE TITLE
Comparison to CiscoCloud/marathon-consul

### ISSUE THREAD

**Issue by mitel** [allegro/marathon-consul#64]
I noticed that this project is based on CiscoCloud's but..
What are the main differences between allegro/marathon-consul and CiscoCloud/marathon-consul and when shall one use one over the other?

**Comment by janisz** [comment]
Hey @mitel 

1. CiscoCloud/marthon-consul copies application information to Consul KV while allegro/marathon-consul register tasks in Consuls Services (it is more similar to CiscoCloud/mesos-consul)
2. CiscoCloud/m.*-consul uses polling while allegro/marathon-consul uses [SSE](https://mesosphere.github.io/marathon/docs/event-bus.html) to detect changes
3. CiscoCloud/marathon-consul is no longer developed (see [comment](https://github.com/CiscoCloud/marathon-consul/issues/17#issuecomment-161678453))

@dankraw Did I miss something? We should put this in README

**Comment by dankraw** [comment]
As @janisz said, our project is a bridge between Marathon and Consul's **service discovery functionality** (not Consul's KV store as in CiscoCloud's project - this is **the main difference**). We were highly influenced by their other project - Mesos-Consul, but we do service registration near real-time (we use Marathon's event bus), not by polling the Mesos api.

So summing it up, if you want to register your services in the service discovery AND you use Marathon - use our project. If you simply use Mesos with some other framework on top of it - use Mesos-Consul.

If you're interested in the Consul's KV functionality - use CiscoCloud's Marathon-Consul.

**Comment by mitel** [comment]
thank you, appreciated guys

**Comment by dankraw** [comment]
Oh, and of course both Marathon-consul projects can work together as Marathon supports multiple event bus callbacks, so you can have your services and KV-data all together.
