### ISSUE TITLE
Running marathon-consul as a Docker container via Marathon

### ISSUE THREAD

**Issue by mitel** [allegro/marathon-consul#65]
Would you recommend running marathon-consul in a lightweight Docker container via Marathon? Any particular setup needed which is not obvious from the README?

Thank you

**Comment by janisz** [comment]
In our setup we run marathon-consul on every Marathon Master and marathon callback is pointing to localhost. This solution remove network overhead, and Marathon Masters proxing.
Deploying marathon-consul on Mesos is also possible but then you need to manually register subscription in Marathon so this is not recommend.
