### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by jogster** [allegro/marathon-consul#71]
Hi Guys, I was using the original ciscocloud/marathon-consul in a docker image (for coreos) and used the Dockerfile supplied with the project. I have created a Dockerfile by pulling down the distro. I would prefer to build from source, I am a bit lost how to create a Dockerfile for your project as I have no real experience with golang... Can you anyone help please?

======================

Ok, managed to hack the ciscocloud/marathon-consul file, very simple just used the Makefile and removed the test tag from the build target.

The launch.sh is again from ciscocloud/marathon-consul 

===== DOCKERFILE =====
FROM gliderlabs/alpine:3.2
MAINTAINER Brian Hicks <brian@brianthicks.com>

RUN apk add --update ca-certificates bash
COPY launch.sh /launch.sh

COPY . /go/src/github.com/allegro/marathon-consul
RUN apk add make go git mercurial \
  && cd /go/src/github.com/allegro/marathon-consul \
  && export GOPATH=/go \
  && make build \
  && mv /go/src/github.com/allegro/marathon-consul/bin/marathon-consul /bin/marathon-consul \
  && rm -rf /go \
  && apk del --purge go git mercurial

ENTRYPOINT ["/launch.sh"]

**Comment by janisz** [comment]
Hi @jogster 

Thanks for submitting issue. Your "hack" looks legit and if you prepare pull request I'll be happy to merge it.

**Comment by jogster** [comment]
Sure — let me figure out how to do that.

**Comment by jogster** [comment]
Just forked the repo and added all my changes -- please pull it back to the main branch if OK.
