### ISSUE TITLE
Support multiple marathon apps with same consul service name

### ISSUE THREAD

**Issue by janisz** [allegro/marathon-consul#72]
Currently [README](https://github.com/allegro/marathon-consul#known-limitations) states

> Every marathon application needs to have a unique service name in Consul.

We should handle this case, because it could be used for green blue deployment.

Changes are required in [`deregisterAllAppServices`](https://github.com/allegro/marathon-consul/blob/c967babe5c34637f3913c25fe72733db2c1c75bc/web/event_handler.go#L246) to deregister only tasks for this app

**Comment by dankraw** [comment]
related to #42 and #35
