### ISSUE TITLE
Can we include all labels: values in the service definition written to consul...

### ISSUE THREAD

**Issue by jogster** [allegro/marathon-consul#75]
I am trying to recreate the functionality between ciscocloud/marathonpconsul and ciscocloud/haproxy-consul

In the original setup the full service definition as described in marathon was inserted straight into kv's in consul.

I can see this function:

func (c *Consul) marathonTaskToConsulService(task *apps.Task, app *apps.App) (*consulapi.AgentServiceRegistration, error) {
	IP, err := utils.HostToIPv4(task.Host)
	if err != nil {
		return nil, err
	}
	serviceAddress := IP.String()

	return &consulapi.AgentServiceRegistration{
		ID:      task.ID.String(),
		Name:    app.ConsulServiceName(),
		Port:    task.Ports[0],
		Address: serviceAddress,
	--->	Tags:    c.marathonLabelsToConsulTags(app.Labels), <----
		Checks:  c.marathonToConsulChecks(task, app.HealthChecks, serviceAddress),
	}, nil
}

I would have assumed that it would have picked up all these labels from my service definition:

"ports": [10000],
"labels": {
     "consul": "basic-3",
     "HAPROXY_HTTP": "true",
     "HTTP_PORT_IDX_0_NAME": "basic-3",
     "HTTP_PORT_IDX_10000_NAME": "basic-3"
  },

but it doesn't...

Additionally I wanted to pull in the ports.

Any advice?

**Comment by janisz** [comment]
[Here](https://github.com/janisz/marathon-consul-playground/blob/advanced_ha_proxy/haproxy.cfg.ctmpl) simple VM that demonstrates how marathon-consul works with haproxy (including tags). 

In [usage](https://github.com/allegro/marathon-consul/blob/master/README.md#usage) you can find description how to register tasks with tags:

> Labels with tag value will be converted to Consul tags, e.g. (note: consul-tag is set to marathon) labels: ["public":"tag", "varnish":"tag", "env": "test"] → tags: ["public", "varnish", "marathon"]

So to distinguish services avaliable over HTTP you can set marathon label to `" http":"tag"` and than handle it differently in consul template.

**Comment by jogster** [comment]
Thanks -- that clears it up!
