### ISSUE TITLE
ERRO[0060] An error occured while performing sync        error=Can't get Consul services: No Consul client available in agents cache

### ISSUE THREAD

**Issue by BCWilsonDotCom** [allegro/marathon-consul#76]
Anyone seen this error before?

INFO[0000] Starting marathon-consul                      Version=0.3.6
INFO[0000] Sending metrics to stdout
INFO[0000] Listening                                     Port=:4000
INFO[0000] Marathon-consul sync job started              Force=false Interval=1m0s Leader=
DEBU[0000] Asking Marathon for leader                    Location=localhost:8080
DEBU[0000] Sending GET request to marathon               Location=localhost:8080 Protocol=http Uri=/v2/leader
INFO[0000] Marathon-consul sync leader mode set to resolved hostname  Leader=mesos-master1:8080
DEBU[0000] Node has leadership                           Node=mesos-master1:8080
INFO[0000] Syncing services started
DEBU[0000] Asking Marathon for apps                      Location=localhost:8080
DEBU[0000] Sending GET request to marathon               Location=localhost:8080 Protocol=http Uri=/v2/apps?embed=apps.tasks&label=consul
ERRO[0060] An error occured while performing sync        error=Can't get Consul services: No Consul client available in agents cache

**Comment by janisz** [comment]
Hi @BCWilsonDotCom

This error occurs when there is no consul agents in cache. This is becouse you don't have any application in marathon that should be registered in consul so we cannot fill consul agents cache. When you deploy at least one application with consul tag, this error disappear.

**Comment by BCWilsonDotCom** [comment]
Thanks for the explanation!
