### ISSUE TITLE
Consul does not support dots in service names for DNS queries

### ISSUE THREAD

**Issue by avthart** [allegro/marathon-consul#81]
Services names must not contain a dot (.) otherwise you could not use the Consul DNS API. For example
a Marathon App with id "/demo/hello/world" is registered by default as Consul Service "demo.hello.world"

From Consul DNS API documentation (https://www.consul.io/docs/agent/services.html):
"DNS-compliant service and tag names may contain any alpha-numeric characters, as well as dashes. Dots are not supported because Consul internally uses them to delimit service tags."

It would be nice if you could implement a different naming strategy, e.g. use dashes instead of dots.

Current workaround for us is to specify a custom consul service name.

**Comment by janisz** [comment]
Hi @avthart 

Good point and it's quite easy to fix, require changing dot to dash [here](https://github.com/allegro/marathon-consul/blob/f333d59df11663cf664dbdde8984d122db5cebba/apps/app.go#L49). Unfortunately we will lost backward compatibility with services registered with dots in name. On the other hand we could just drop that functionality and force user to provide service name for the app.
@dankraw What do you think?

**Comment by dankraw** [comment]
@avthart good point 
@janisz I think we can solve the problem by providing configurable separator, we won't loose backward compatibility this way

**Comment by avthart** [comment]
@janisz I would not drop this functionality. It is a nice feature to have a (standardized) naming strategy for consul services.
@dankraw Sound good to have a configurable separator, so that existing infrastructures which are using marathon-consul, won 't have to change anything.

**Comment by janisz** [comment]
I like the idea of configurable separator. So the changes are required in 
- [AppId.ConsulServiceName](https://godoc.org/github.com/allegro/marathon-consul/apps#AppId.ConsulServiceName)
- [Config](https://godoc.org/github.com/allegro/marathon-consul/config#Config)

tests and readme will also need to be updated
I think the separator could be provided as a parameter or as a global variable that will be setup at the beginning in `main`.

**Comment by avthart** [comment]
Thx!

**Comment by janisz** [comment]
You are welcome. We will do formal release when after go 1.7 release.
