### ISSUE TITLE
Support multiple ports

### ISSUE THREAD

**Issue by avthart** [allegro/marathon-consul#89]
Most of our marathon apps have only one portMapping but sometimes we have an app with multiple ports where one of the ports will be used for (http) health checks. 

In newer versions of marathon you can specify labels for each port in the "portMappings". Maybe this is something we can use to register services in consul?

Example marathon app:
```
{
  "id": "/hello-world",
  "cpus": 0.1,
  "mem": 256,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "my-hello-world:latest",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8080,
          "hostPort": 0,
          "protocol": "tcp",
          "name": "api",
          "labels": { 
              "consul": "helloworld-api"
          }
        },
        {
          "containerPort": 8081,
          "hostPort": 0,
          "protocol": "tcp",
          "name": "actuator",
          "labels": {
              "consul": "helloworld-health"
          }
        }
      ]
   }
  },
  "healthChecks": [
    {
      "path": "/health",
      "protocol": "HTTP",
      "portIndex": 1,
      "gracePeriodSeconds": 300,
      "intervalSeconds": 10,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ]
}
```

**Comment by janisz** [comment]
This could be great addition to marathon-consul. Internally we don't use docker containers a lot, so it's no priority for us to support docker port labels. 
Although if you need this feature we can help you to deliver it. Changes are required in [`consul.marathonTaskToConsulService`](https://github.com/allegro/marathon-consul/blob/master/consul/consul.go#L210). I recommend do it step by step:

- [ ] Detect which port should be registered basde on port labels (in no one specified 0 wil be used)
- [ ] Merge port labels with app labels (How to handle conflicts?)
- [ ] Generate multiple consul services from one marathon task

If you need any guidance please reach us here or with e-mail/twitter/hangout so we can help you.

**Comment by pbetkier** [comment]
It appears we have a similar need now internally – registering an app under more than 1 name with different ports, but with the same healthcheck. It's not related to docker though. I'm coding such solution right now, will open a PR for discussion in a couple of days.

**Comment by karthimohan** [comment]
@pbetkier Thanks for merging #99 Just wondering if you have any timeline on when this #89 Enhancement will be available for testing.

**Comment by pbetkier** [comment]
@karthimohan I'd say 2 weeks time sounds realistic. We still need to test #99 internally.

**Comment by karthimohan** [comment]
Thanks @pbetkier Looking forward for this feature.

**Comment by lwille** [comment]
Thanks for the good work, I'm also be interested in testing once it's ready :)

**Comment by janisz** [comment]
@lwille Working feature is on `development` branch. It's working on one of our test environment but only one or two applications are using multi prot registering. If you like to test it you can build it from source.
