### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by vi4m** [allegro/marathon-consul#9]
It would be nice to push deb pacakages to bintray apt repository. 

We(Allegro projects - andamio and ralph) do it after successfull CI build. Maybe you will find it handy: https://github.com/allegro/ralph/blob/ng/packaging/upload-package.sh

**Comment by kamilchm** [comment]
https://dzone.com/articles/releasing-cross-platform-go-binaries-using-goxc-an

**Comment by dankraw** [comment]
@vi4m thanks, we're already using goxc.
The binaries will be pushed to [github releases](https://github.com/allegro/marathon-consul/releases) and [bintray](https://bintray.com/allegro/deb/marathon-consul/view)
