### ISSUE TITLE
APT repository not signed?

### ISSUE THREAD

**Issue by eyalzek** [allegro/marathon-consul#90]
Following the APT repository instructions gives me the following output when I run `apt-get update`:

    W: The repository 'http://dl.bintray.com/v1/content/allegro/deb  Release' is not signed.
    N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
    N: See apt-secure(8) manpage for repository creation and user configuration details.

Which in turn fails my project because the package cannot be authenticated.

**Comment by dankraw** [comment]
@eyalzek could you try again now, please?

**Comment by eyalzek** [comment]
Seems to be working. I will try again tomorrow at work and update, thanks!

**Comment by dankraw** [comment]
Thanks for the info. Looks like Bintray needs some delay between pushing binaries and signing them. I've fixed our release plan. I'm closing the issue, please reopen if needed.

**Comment by eyalzek** [comment]
Working now, thanks!
